/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Resources } from '../models/resources';
export interface Document {
  filePath?: string;
  fileSize?: number;
  fileType?: string;
  id?: number;
  name?: string;
  resource?: Resources;
  type?: 'PNG' | 'PDF' | 'JPEG' | 'JPG';
}
