/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Hackathon {
  name?: string;
  id?: number;
  maxTeamSize?: number;
  joinedTeamId?: number; // Add this optional property
}
