/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Quiz } from '../models/quiz';
export interface Question {
  answers?: Array<string>;
  correctAnswerIndex?: number;
  id_question?: number;
  questionText?: string;
  quiz?: Quiz;
}
