/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Question } from '../models/question';
import { UserQuizScore } from '../models/user-quiz-score';
import { Workshop } from '../models/workshop';
export interface Quiz {
  id_quiz?: number;
  published?: boolean;
  questions?: Array<Question>;
  title?: string;
  userQuizScores?: Array<UserQuizScore>;
  workshop?: Workshop;
}
