/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Document } from '../models/document';
import { ImageModel } from '../models/image-model';
import { Workshop } from '../models/workshop';
export interface Resources {
  description?: string;
  documents?: Array<Document>;
  id?: number;
  image?: string;
  images?: Array<ImageModel>;
  name?: string;
  niveau?: 'Beginner' | 'Intermediate' | 'Expert';
  workshop?: Workshop;
}
