/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Team } from '../models/team';
import { TeamMembers } from '../models/team-members';
/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TeamDiscussion {
  id?: number;
  message?: string;
  messageType?: 'TEXT' | 'IMAGE' | 'FILE' | 'EMOJI';
  isRead?: boolean;
  createdAt?: string | Date;
  team?: Team;
  teamMember?: TeamMembers;
  senderName?: string; // For UI display
  senderRole?: 'LEADER' | 'MEMBER' | 'MENTOR' | 'Unknown'; // For UI display
  // New fields
  reactions?: MessageReaction[];
  isPinned?: boolean;
  isEdited?: boolean;
  isForwarded?: boolean;
  quotedMessage?: TeamDiscussion;
  fileUrl?: string;
  fileSize?: number;
  fileType?: string;
  thumbnailUrl?: string;
  emoji?: string;
  status?: 'SENT' | 'DELIVERED' | 'READ';
  isTyping?: boolean;
  lastEditedAt?: string | Date;
  deletedAt?: string | Date;
  isDeleted?: boolean;
}

export interface MessageReaction {
  emoji: string;
  count: number;
  users: number[];
}
