/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Team } from '../models/team';
import { TeamMembers } from '../models/team-members';
/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TeamDiscussion {
  id?: number;
  message?: string;
  messageType?: 'TEXT' | 'IMAGE' | 'FILE' | 'EMOJI';
  isRead?: boolean;
  createdAt?: string | Date;
  team?: Team;
  teamMember?: TeamMembers;
  senderName?: string; // For UI display
  senderRole?: 'LEADER' | 'MEMBER' | 'MENTOR' | 'Unknown'; // For UI display
}
