/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Quiz } from '../models/quiz';
import { User } from '../models/user';
export interface UserQuizScore {
  id?: number;
  quiz?: Quiz;
  score?: number;
  user?: User;
}
