/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Quiz } from '../models/quiz';
import { Resources } from '../models/resources';
import { User } from '../models/user';
export interface Workshop {
  description?: string;
  id?: number;
  name?: string;
  photo?: string;
  quiz?: Quiz;
  resources?: Array<Resources>;
  theme?: 'Cloud' | 'AI' | 'Machine_Learning' | 'DevOps' | 'Web' | 'IoT' | 'Video_Games';
  user?: User;
}
