/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TeamMembers } from '../../models/team-members';

export interface GetAllTeamMembers$Params {
}

export function getAllTeamMembers(http: HttpClient, rootUrl: string, params?: GetAllTeamMembers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TeamMembers>>> {
  const rb = new RequestBuilder(rootUrl, getAllTeamMembers.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TeamMembers>>;
    })
  );
}

getAllTeamMembers.PATH = '/api/team-members/all';
