/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserQuizScore } from '../../models/user-quiz-score';

export interface GetUserScores$Params {
  userId: number;
}

export function getUserScores(http: HttpClient, rootUrl: string, params: GetUserScores$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserQuizScore>>> {
  const rb = new RequestBuilder(rootUrl, getUserScores.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserQuizScore>>;
    })
  );
}

getUserScores.PATH = '/score/user/{userId}';
