/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserQuizScore } from '../../models/user-quiz-score';
import { UserQuizScoreRequest } from '../../models/user-quiz-score-request';

export interface SaveScore$Params {
      body: UserQuizScoreRequest
}

export function saveScore(http: HttpClient, rootUrl: string, params: SaveScore$Params, context?: HttpContext): Observable<StrictHttpResponse<UserQuizScore>> {
  const rb = new RequestBuilder(rootUrl, saveScore.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserQuizScore>;
    })
  );
}

saveScore.PATH = '/score';
