/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Workshop } from '../../models/workshop';

export interface GetAllWorkshops$Params {
}

export function getAllWorkshops(http: HttpClient, rootUrl: string, params?: GetAllWorkshops$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Workshop>>> {
  const rb = new RequestBuilder(rootUrl, getAllWorkshops.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Workshop>>;
    })
  );
}

getAllWorkshops.PATH = '/workshops';
