/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Resources } from '../../models/resources';

export interface CreateOrUpdateResource$Params {
      body: Resources
}

export function createOrUpdateResource(http: HttpClient, rootUrl: string, params: CreateOrUpdateResource$Params, context?: HttpContext): Observable<StrictHttpResponse<Resources>> {
  const rb = new RequestBuilder(rootUrl, createOrUpdateResource.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Resources>;
    })
  );
}

createOrUpdateResource.PATH = '/resources';
