/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { QuizControllerService } from './services/quiz-controller.service';
import { QuestionControllerService } from './services/question-controller.service';
import { RessourcesControllerService } from './services/ressources-controller.service';
import { UserControllerService } from './services/user-controller.service';
import { TeamControllerService } from './services/team-controller.service';
import { TeamMembersControllerService } from './services/team-members-controller.service';
import { TeamDiscussionControllerService } from './services/team-discussion-controller.service';
import { SkillControllerService } from './services/skill-controller.service';
import { RoleControllerService } from './services/role-controller.service';
import { WorkshopControllerService } from './services/workshop-controller.service';
import { UserQuizScoreControllerService } from './services/user-quiz-score-controller.service';
import { ResourcesControllerService } from './services/resources-controller.service';
import { AuthControllerService } from './services/auth-controller.service';
import { WebSocketTestControllerService } from './services/web-socket-test-controller.service';
import { QuizCertificateControllerService } from './services/quiz-certificate-controller.service';
import { CustomErrorControllerService } from './services/custom-error-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    QuizControllerService,
    QuestionControllerService,
    RessourcesControllerService,
    UserControllerService,
    TeamControllerService,
    TeamMembersControllerService,
    TeamDiscussionControllerService,
    SkillControllerService,
    RoleControllerService,
    WorkshopControllerService,
    UserQuizScoreControllerService,
    ResourcesControllerService,
    AuthControllerService,
    WebSocketTestControllerService,
    QuizCertificateControllerService,
    CustomErrorControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
