/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Document } from './models/document';
export type { GrantedAuthority } from './models/granted-authority';
export type { Hackathon } from './models/hackathon';
export type { ImageModel } from './models/image-model';
export type { MonitorEvaluation } from './models/monitor-evaluation';
export type { PasswordDto } from './models/password-dto';
export type { Question } from './models/question';
export type { Quiz } from './models/quiz';
export type { Resources } from './models/resources';
export type { Role } from './models/role';
export type { Skill } from './models/skill';
export type { SponsorApplication } from './models/sponsor-application';
export type { Team } from './models/team';
export type { TeamDiscussion } from './models/team-discussion';
export type { TeamMembers } from './models/team-members';
export type { User } from './models/user';
export type { UserQuizScore } from './models/user-quiz-score';
export type { UserQuizScoreRequest } from './models/user-quiz-score-request';
export type { Workshop } from './models/workshop';
