/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { QuizControllerService } from './services/quiz-controller.service';
export { QuestionControllerService } from './services/question-controller.service';
export { RessourcesControllerService } from './services/ressources-controller.service';
export { UserControllerService } from './services/user-controller.service';
export { TeamControllerService } from './services/team-controller.service';
export { TeamMembersControllerService } from './services/team-members-controller.service';
export { TeamDiscussionControllerService } from './services/team-discussion-controller.service';
export { SkillControllerService } from './services/skill-controller.service';
export { RoleControllerService } from './services/role-controller.service';
export { WorkshopControllerService } from './services/workshop-controller.service';
export { UserQuizScoreControllerService } from './services/user-quiz-score-controller.service';
export { ResourcesControllerService } from './services/resources-controller.service';
export { AuthControllerService } from './services/auth-controller.service';
export { WebSocketTestControllerService } from './services/web-socket-test-controller.service';
export { QuizCertificateControllerService } from './services/quiz-certificate-controller.service';
export { CustomErrorControllerService } from './services/custom-error-controller.service';
