/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Resources } from '../../models/resources';

export interface CreateResource$Params {
  workshopId: number;
      body?: {
'resource': string;
'documents'?: Array<Blob>;
'images'?: Array<Blob>;
}
}

export function createResource(http: HttpClient, rootUrl: string, params: CreateResource$Params, context?: HttpContext): Observable<StrictHttpResponse<Resources>> {
  const rb = new RequestBuilder(rootUrl, createResource.PATH, 'post');
  if (params) {
    rb.path('workshopId', params.workshopId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Resources>;
    })
  );
}

createResource.PATH = '/api/workshops/{workshopId}/resources';
