/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Resources } from '../../models/resources';

export interface GetResource$Params {
  workshopId: number;
  resourceId: number;
}

export function getResource(http: HttpClient, rootUrl: string, params: GetResource$Params, context?: HttpContext): Observable<StrictHttpResponse<Resources>> {
  const rb = new RequestBuilder(rootUrl, getResource.PATH, 'get');
  if (params) {
    rb.path('workshopId', params.workshopId, {});
    rb.path('resourceId', params.resourceId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Resources>;
    })
  );
}

getResource.PATH = '/api/workshops/{workshopId}/resources/{resourceId}';
