/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SendTestMessage$Params {
  teamId: number;
  senderName?: string;
  message?: string;
}

export function sendTestMessage(http: HttpClient, rootUrl: string, params: SendTestMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: {
};
}>> {
  const rb = new RequestBuilder(rootUrl, sendTestMessage.PATH, 'post');
  if (params) {
    rb.path('teamId', params.teamId, {});
    rb.query('senderName', params.senderName, {});
    rb.query('message', params.message, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: {
      };
      }>;
    })
  );
}

sendTestMessage.PATH = '/api/websocket-test/send/{teamId}';
