/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { downloadCertificate } from '../fn/quiz-certificate-controller/download-certificate';
import { DownloadCertificate$Params } from '../fn/quiz-certificate-controller/download-certificate';

@Injectable({ providedIn: 'root' })
export class QuizCertificateControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `downloadCertificate()` */
  static readonly DownloadCertificatePath = '/certificates/download';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadCertificate()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadCertificate$Response(params: DownloadCertificate$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return downloadCertificate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadCertificate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadCertificate(params: DownloadCertificate$Params, context?: HttpContext): Observable<Blob> {
    return this.downloadCertificate$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

}
