/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SendMessageRest$Params {
  teamId: number;
  teamMemberId: number;
  messageType?: 'TEXT' | 'IMAGE' | 'FILE' | 'EMOJI';
  Authorization: string;
      body: {
[key: string]: string;
}
}

export function sendMessageRest(http: HttpClient, rootUrl: string, params: SendMessageRest$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, sendMessageRest.PATH, 'post');
  if (params) {
    rb.path('teamId', params.teamId, {});
    rb.query('teamMemberId', params.teamMemberId, {});
    rb.query('messageType', params.messageType, {});
    rb.header('Authorization', params.Authorization, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

sendMessageRest.PATH = '/api/team-discussions/send/{teamId}';
