/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { Team } from '../../models/team';

export interface CreateTeam$Params {
  hackathonId: number;
  leaderId: number;
  body: Team;
}

export function createTeam(http: HttpClient, rootUrl: string, params: CreateTeam$Params, context?: HttpContext): Observable<StrictHttpResponse<Team>> {
  const rb = new RequestBuilder(rootUrl, createTeam.PATH, 'post');
  if (params) {
    rb.path('hackathonId', params.hackathonId, {});
    rb.path('leaderId', params.leaderId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context }) // Changed to json
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Team>; // Return Team instead of empty object
    })
  );
}

createTeam.PATH = '/api/teams/create/{hackathonId}/{leaderId}';